### ISSUE TITLE
error[E0277]: the trait bound `{integer}: SampleRange<_>` is not satisfied

### ISSUE THREAD

**Issue by xrandx** [zhanglun/pavo#1]
The issue shows on Windows 11.

I changed *scheduler.rs*.

add line 
```rust
use rand::{Rng, distributions::Uniform};
```

and change line 97 
```rust
let idx = rng.gen_range(0, list.len());
```

into
```rust
let idx = rng.sample(Uniform::new_inclusive(0, list.len()));
```

The problem will be solved.

**Comment by zhanglun** [comment]
Thank you for your reminder. https://github.com/zhanglun/pavo/commit/95ff60e8d22db39d9cea763499fc43f053ae9a68 

Please help me to test it if you can. I will close the issue if it solved

**Comment by xrandx** [comment]
> 

Yep. It was solved.
